const express = require('express');
const router = express.Router();
const userLogin= require('../../Controller/authController/loginController');
const userRegister=require('../../Controller/authController/registerController');
const authenticateToken = require('../../middlewares/authenticateToken');
router.post('/login',userLogin.login);
router.post('/forgotPassword',userLogin.forgetPassword);
router.post('/ResetPassword/:token',userLogin.resetPassword);
router.post('/register',userRegister);
router.get('/logout', userLogin.logout);
module.exports = router;
